//go:generate go run github.com/magefile/mage -d ../../.. generate:platforms
package utils

var Platforms = []string{
	"aix-ppc64",
	"android-386",
	"android-amd64",
	"android-arm",
	"android-arm64",
	"darwin-386",
	"darwin-amd64",
	"darwin-arm",
	"darwin-arm64",
	"dragonfly-amd64",
	"freebsd-386",
	"freebsd-amd64",
	"freebsd-arm",
	"js-wasm",
	"linux-386",
	"linux-amd64",
	"linux-arm",
	"linux-arm64",
	"linux-mips",
	"linux-mips64",
	"linux-mips64le",
	"linux-mipsle",
	"linux-ppc64",
	"linux-ppc64le",
	"linux-s390x",
	"nacl-386",
	"nacl-amd64p32",
	"nacl-arm",
	"netbsd-386",
	"netbsd-amd64",
	"netbsd-arm",
	"openbsd-386",
	"openbsd-amd64",
	"openbsd-arm",
	"plan9-386",
	"plan9-amd64",
	"plan9-arm",
	"solaris-amd64",
	"windows-386",
	"windows-amd64",
	"windows-arm",
}
