style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/chirino/uc
options:
  # commits:
  #    filters:
  #      Type:
  #        - feat
  #        - fix
  #        - bug
  #        - perf
  #        - refactor
  commit_groups:
     title_maps:
       feat: Features
       chore: Chores
       fix: Bug Fixes
       perf: Performance Improvements
       refactor: Code Refactoring
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject

  notes:
    keywords:
      - BREAKING CHANGE
      - RELEASE NOTES
